### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by liuhaogui** [jkstack/natpass#14]
- 代码目录结构：可否参照下相关golang开源项目或者规范靠一下呢，暂可忽略
- windows支持：既然当前只支持windows vnc，不知是否有调测，配置文件是否单独抽出windows支持的配置路径格式，或者程序处理转义路径形式。windows报错，启动panic,尴尬
- panic： 直接使用panic处理所有错误，太硬了，出问题哪里抛出的都不一定能直接找到，估摸的一层一层去找了，生产环境定然不能直接这样，推荐log信息埋点加时间event关键词是否会更友好点
- 直接上tls： 个人感觉有必要，也有点硬，门槛拉高了，只是想使用下，或者放置个默认试用证书？ 或者配置tls开启、关闭 客服考虑下 
- 开发者文档：暂可忽略

目前看想试用下跑起来有点费劲。测试各种panic 泪崩

**Comment by liuhaogui** [comment]
贴点日志

server
```
2021/11/23 13:27:41 [INFO]listen on 6154
panic: runtime error: index out of range [0] with length 0

goroutine 20 [running]:
github.com/lwch/logging.(*rotateSizeLogger).rotate(0xc00009c000)
	/Users/alex.liu/Golang/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/rotate_size.go:95 +0xcdd
github.com/lwch/logging.Logger.Error(0x139eb90, 0xc00009c000, 0x134d899, 0x27, 0xc0000134d0, 0x3, 0x3)
	/Users/alex.liu/Golang/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:63 +0x35
github.com/lwch/logging.Error(...)
	/Users/alex.liu/Golang/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:30
natpass/code/server/handler.(*Handler).Handle(0xc0000ae000, 0x13a1358, 0xc000094020)
	/Users/alex.liu/Golang/src/github.com/lwch/natpass/code/server/handler/handler.go:68 +0x11e
created by main.run
	/Users/alex.liu/Golang/src/github.com/lwch/natpass/code/server/main.go:116 +0xce
exit status 2
```

**Comment by liuhaogui** [comment]
```
 + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:68) natpass/code/server/handler.(*Handler).Handle
2021/11/23 13:26:39 [ERROR]read handshake from 172.16.19.245:51606 8 times, err=read tcp 172.26.21.214:6154->172.16.19.245:51606: read: connection reset by peer
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:68) natpass/code/server/handler.(*Handler).Handle
2021/11/23 13:26:39 [ERROR]read handshake from 172.16.19.245:51606 9 times, err=read tcp 172.26.21.214:6154->172.16.19.245:51606: read: connection reset by peer
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:68) natpass/code/server/handler.(*Handler).Handle
2021/11/23 13:26:39 [ERROR]read handshake from 172.16.19.245:51606 10 times, err=read tcp 172.26.21.214:6154->172.16.19.245:51606: read: connection reset by peer
  + (/root/go/pkg/mod/github.com/lwch/logging@v0.0.0-20211115073745-0db19179db17/log.go:30) github.com/lwch/logging.Error
  + (/build/code/server/handler/handler.go:68) natpass/code/server/handler.(*Handler).Handle
```

**Comment by liuhaogui** [comment]
windows

![image](https://user-images.githubusercontent.com/47664337/142976271-c81ad795-02ba-40cc-8023-1f487ebef457.png)

**Comment by lwch** [comment]
上面这个错误可能是因为配置了错误的log.rotate数值造成的，该数值必须大于0，下一版本中会加入配置文件的参数规范性检查。

* golang本身的代码组织目录结构比较松散，且建议单个文件或方法不宜过长，我这边目前做了一些约定
   * 以`h_`开头的文件表示API接口，供前端调用
   * 以`send_`开头的文件表示数据包拼装，用于网络通信
   * 跨平台编译文件遵从golang的规范，使用build tag或文件名后缀
* 对于panic的说法，在natpass中原则上只要影响程序正常启动的，直接panic不进行捕获，在运行时产生的错误会有error log记录
* tls是为了保证通信安全，目前let's encrypt项目推进了这么多年就是为了提高网络通信的安全性的，因此在natpass项目中将不会提供不安全的明文传输

最后，感谢您的建议，natpass距离1.0.0正式版release还有很多功能没有完成，因此开发文档较少，我会在开发过程中尽量补齐的。

**Comment by lwch** [comment]
v0.8.0版本已支持非tls加密连接
